package ru.itmo.blps.ozon.entity;

public enum OrderStatus {
    ORDER_RECEIVED,
    ORDER_CONTENTS_LOADED,
    STOCK_AVAILABILITY_CHECKED,
    ITEMS_RESERVED,
    SELLER_CONFIRMED,
    PICKING_TASK_CREATED,
    ORDER_PICKED,
    ORDER_PACKED,
    HANDED_TO_DELIVERY,
    DELIVERED_AND_CLOSED,
    CANCELLED
}
