package ru.itmo.blps.ozon.notification;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

@Repository
public class NotificationEventRepository {

    private final JdbcTemplate jdbcTemplate;

    public NotificationEventRepository(JdbcTemplate notificationJdbcTemplate) {
        this.jdbcTemplate = notificationJdbcTemplate;
    }

    public void initializeSchema() {
        jdbcTemplate.execute("""
                create table if not exists notification_events (
                    id bigint generated by default as identity primary key,
                    order_id bigint not null,
                    type varchar(64) not null,
                    message varchar(512) not null,
                    created_at timestamp not null
                )
                """);
    }

    public Long prepareOrderCreated(String customerName, LocalDateTime createdAt) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            java.sql.PreparedStatement statement = connection.prepareStatement(
                """
                        insert into notification_events (order_id, type, message, created_at)
                        values (?, ?, ?, ?)
                        """,
                    new String[]{"id"}
            );
            statement.setLong(1, 0L);
            statement.setString(2, "ORDER_CREATED");
            statement.setString(3, "Preparing new order for " + customerName);
            statement.setTimestamp(4, Timestamp.valueOf(createdAt));
            return statement;
        }, keyHolder);
        return Objects.requireNonNull(keyHolder.getKey()).longValue();
    }

    public void attachOrder(Long notificationId, Long orderId, String customerName) {
        jdbcTemplate.update(
                """
                        update notification_events
                        set order_id = ?, message = ?
                        where id = ?
                        """,
                orderId,
                "New order for " + customerName,
                notificationId
        );
    }

    public List<NotificationResponse> findAll() {
        return jdbcTemplate.query(
                """
                        select id, order_id, type, message, created_at
                        from notification_events
                        order by id
                        """,
                this::mapRow
        );
    }

    public long count() {
        Long count = jdbcTemplate.queryForObject("select count(*) from notification_events", Long.class);
        return count == null ? 0 : count;
    }

    public void deleteAll() {
        jdbcTemplate.update("delete from notification_events");
    }

    private NotificationResponse mapRow(ResultSet resultSet, int rowNumber) throws SQLException {
        return new NotificationResponse(
                resultSet.getLong("id"),
                resultSet.getLong("order_id"),
                resultSet.getString("type"),
                resultSet.getString("message"),
                resultSet.getTimestamp("created_at").toLocalDateTime()
        );
    }
}
