spring.datasource.jndi-name=${WILDFLY_DATASOURCE_JNDI:java:/PostgresDS}
app.tx.orders.jndi-name=${WILDFLY_DATASOURCE_JNDI:java:/PostgresDS}
app.tx.notifications.jndi-name=${WILDFLY_NOTIFICATION_DATASOURCE_JNDI:java:/NotificationDS}

spring.jpa.properties.hibernate.transaction.coordinator_class=jta
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform

app.notifications.jms.enabled=${APP_NOTIFICATIONS_JMS_ENABLED:true}
app.jms.host=${APP_JMS_HOST:rabbitmq}
app.jms.port=${APP_JMS_PORT:5672}
app.jms.username=${APP_JMS_USERNAME:guest}
app.jms.password=${APP_JMS_PASSWORD:guest}
app.jms.queue-name=${APP_JMS_QUEUE_NAME:order.status.queue}
