spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:${DB_PORT:5434}/studs}
spring.datasource.username=${DB_USERNAME:s368925}
spring.datasource.password=${DB_PASSWORD:5mCSFOGOnfrbfJeC}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.sql.init.mode=never

app.security.seed.enabled=${APP_SECURITY_SEED_ENABLED:false}
app.security.seed.manager-password=${APP_SECURITY_MANAGER_PASSWORD:manager123}
app.security.seed.warehouse-password=${APP_SECURITY_WAREHOUSE_PASSWORD:warehouse123}
app.security.seed.delivery-password=${APP_SECURITY_DELIVERY_PASSWORD:delivery123}
app.security.seed.admin-password=${APP_SECURITY_ADMIN_PASSWORD:admin123}
