server.port=8081
spring.application.name=notification_service

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.sql.init.mode=never

app.jms.host=localhost
app.jms.port=5672
app.jms.username=guest
app.jms.password=guest
app.jms.queue-name=order.status.queue